// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubscribersWebAPI.Data;

#nullable disable

namespace SubscribersWebAPI.Migrations
{
    [DbContext(typeof(SubscriberContext))]
    [Migration("20251117084142_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubscribersWebAPI.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionNumber")
                        .IsUnique();

                    b.ToTable("Subscribers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Stockholm",
                            CreatedAt = new DateTime(2025, 5, 17, 8, 41, 41, 700, DateTimeKind.Utc).AddTicks(8833),
                            DeliveryAddress = "Storgatan 10",
                            Email = "anna.andersson@email.se",
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Andersson",
                            PhoneNumber = "070-123456",
                            PostalCode = "12345",
                            SubscriptionNumber = "SUB001",
                            SubscriptionStartDate = new DateTime(2025, 5, 17, 8, 41, 41, 700, DateTimeKind.Utc).AddTicks(8821),
                            SubscriptionType = 4,
                            UpdatedAt = new DateTime(2025, 5, 17, 8, 41, 41, 700, DateTimeKind.Utc).AddTicks(8834)
                        },
                        new
                        {
                            Id = 2,
                            City = "Göteborg",
                            CreatedAt = new DateTime(2025, 8, 17, 8, 41, 41, 700, DateTimeKind.Utc).AddTicks(8841),
                            DeliveryAddress = "Kungsgatan 25",
                            Email = "erik.eriksson@email.se",
                            FirstName = "Erik",
                            IsActive = true,
                            LastName = "Eriksson",
                            PhoneNumber = "070-789012",
                            PostalCode = "41115",
                            SubscriptionNumber = "SUB002",
                            SubscriptionStartDate = new DateTime(2025, 8, 17, 8, 41, 41, 700, DateTimeKind.Utc).AddTicks(8840),
                            SubscriptionType = 1,
                            UpdatedAt = new DateTime(2025, 8, 17, 8, 41, 41, 700, DateTimeKind.Utc).AddTicks(8842)
                        },
                        new
                        {
                            Id = 3,
                            City = "Malmö",
                            CreatedAt = new DateTime(2024, 11, 17, 8, 41, 41, 700, DateTimeKind.Utc).AddTicks(8853),
                            DeliveryAddress = "Drottninggatan 5",
                            Email = "maria.johansson@email.se",
                            FirstName = "Maria",
                            IsActive = true,
                            LastName = "Johansson",
                            PhoneNumber = "070-345678",
                            PostalCode = "21121",
                            SubscriptionNumber = "SUB003",
                            SubscriptionStartDate = new DateTime(2024, 11, 17, 8, 41, 41, 700, DateTimeKind.Utc).AddTicks(8847),
                            SubscriptionType = 4,
                            UpdatedAt = new DateTime(2024, 11, 17, 8, 41, 41, 700, DateTimeKind.Utc).AddTicks(8854)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
